const poses = [
  {id:1, sanskrit:"Navasana", english:"Boat", img:"./imgs/1.svg"},
  {id:2, sanskrit:"Ardha Navasana", english:"Half-Boat", img:"./imgs/2.svg"},
  {id:3, sanskrit:"Dhanurasana", english:"Bow", img:"./imgs/3.svg"},
  {id:4, sanskrit:"Setu Bandha Sarvangasana", english:"Bridge", img:"./imgs/4.svg"},
  {id:5, sanskrit:"Baddha Konasana", english:"Butterfly", img:"./imgs/5.svg"},
  {id:6, sanskrit:"Ustrasana", english:"Camel", img:"./imgs/6.svg"},
  {id:7, sanskrit:"Marjaryasana", english:"Cat", img:"./imgs/7.svg"},
  {id:8, sanskrit:"Bitilasana", english:"Cow", img:"./imgs/8.svg"},
  {id:9, sanskrit:"Utkatasana", english:"Chair", img:"./imgs/9.svg"},
  {id:10, sanskrit:"Balasana", english:"Child's Pose", img:"./imgs/10.svg"},
  {id:11, sanskrit:"Sivasana", english:"Corpse", img:"./imgs/11.svg"},
  {id:12, sanskrit:"Alanasana", english:"Crescent Lunge", img:"./imgs/12.svg"},
  {id:13, sanskrit:"Bakasana", english:"Crow", img:"./imgs/13.svg"},
  {id:14, sanskrit:"Ardha Pincha Mayurasana", english:"Dolphin", img:"./imgs/14.svg"},
  {id:15, sanskrit:"Adho Mukha Svanasana", english:"Downward-Facing Dog", img:"./imgs/15.svg"},
  {id:16, sanskrit:"Garudasana", english:"Eagle", img:"./imgs/16.svg"},
  {id:17, sanskrit:"Utthita Hasta Padangusthasana", english:"Extended Hand to Toe", img:"./imgs/17.svg"},
  {id:18, sanskrit:"Utthita Parsvakonasana", english:"Extended Side Angle", img:"./imgs/18.svg"},
  {id:19, sanskrit:"Pincha Mayurasana", english:"Forearm Stand", img:"./imgs/19.svg"},
  {id:20, sanskrit:"Uttanasana", english:"Forward Bend with Shoulder Opener", img:"./imgs/20.svg"},
  {id:21, sanskrit:"Ardha Chandrasana", english:"Half-Moon", img:"./imgs/21.svg"},
  {id:22, sanskrit:"Adho Mukha Vrksasana", english:"Handstand", img:"./imgs/22.svg"},
  {id:23, sanskrit:"Anjaneyasana", english:"Low Lunge", img:"./imgs/23.svg"},
  {id:24, sanskrit:"Supta Kapotasana", english:"Pigeon", img:"./imgs/24.svg"},
  {id:25, sanskrit:"Eka Pada Rajakapotasana", english:"King Pigeon", img:"./imgs/25.svg"},
  {id:26, sanskrit:"Phalakasana", english:"Plank", img:"./imgs/26.svg"},
  {id:27, sanskrit:"Halasana", english:"Plow", img:"./imgs/27.svg"},
  {id:28, sanskrit:"Parsvottanasana", english:"Pyramid", img:"./imgs/28.svg"},
  {id:29, sanskrit:"Parsva Virabhadrasana", english:"Reverse Warrior", img:"./imgs/29.svg"},
  {id:30, sanskrit:"Paschimottanasana", english:"Seated Forward Bend", img:"./imgs/30.svg"},
  {id:31, sanskrit:"Padmasana", english:"Lotus", img:"./imgs/31.svg"},
  {id:32, sanskrit:"Ardha Matsyendrasana", english:"Half Lord of the Fishes", img:"./imgs/32.svg"},
  {id:33, sanskrit:"Salamba Sarvangasana", english:"Shoulder Stand", img:"./imgs/33.svg"},
  {id:34, sanskrit:"Vasisthasana", english:"Side Plank", img:"./imgs/34.svg"},
  {id:35, sanskrit:"Salamba Bhujangasana", english:"Sphinx", img:"./imgs/35.svg"},
  {id:36, sanskrit:"Hanumanasana", english:"Splits", img:"./imgs/36.svg"},
  {id:37, sanskrit:"Malasana", english:"Squat", img:"./imgs/37.svg"},
  {id:38, sanskrit:"Uttanasana", english:"Standing Forward Bend", img:"./imgs/38.svg"},
  {id:39, sanskrit:"Ashta Chandrasana", english:"Crescent Moon", img:"./imgs/39.svg"},
  {id:40, sanskrit:"Upavistha Konasana", english:"Side Splits", img:"./imgs/40.svg"},
  {id:41, sanskrit:"Vrksasana", english:"Tree", img:"./imgs/41.svg"},
  {id:42, sanskrit:"Trikonasana", english:"Triangle", img:"./imgs/42.svg"},
  {id:43, sanskrit:"Urdhva Mukha Svsnssana", english:"Upward-Facing Dog", img:"./imgs/43.svg"},
  {id:44, sanskrit:"Virabhadrasana One", english:"Warrior One", img:"./imgs/44.svg"},
  {id:45, sanskrit:"Virabhadrasana Two", english:"Warrior Two", img:"./imgs/45.svg"},
  {id:46, sanskrit:"Virabhadrasana Three", english:"Warrior Three", img:"./imgs/46.svg"},
  {id:47, sanskrit:"Urdhva Dhanurasana", english:"Wheel", img:"./imgs/47.svg"},
  {id:48, sanskrit:"Camatkarasana", english:"Wild Thing", img:"./imgs/48.svg"}
]

module.exports = {poses}
