const svg = require('./svg')

const poses = [
  {id:1, sanskrit:"Navasana", english:"Boat", img: svg.svg1},
  {id:2, sanskrit:"Ardha Navasana", english:"Half-Boat", img: svg.svg2},
  {id:3, sanskrit:"Dhanurasana", english:"Bow", img: svg.svg3},
  {id:4, sanskrit:"Setu Bandha Sarvangasana", english:"Bridge", img: svg.svg4},
  {id:5, sanskrit:"Baddha Konasana", english:"Butterfly", img: svg.svg5},
  {id:6, sanskrit:"Ustrasana", english:"Camel", img: svg.svg6},
  {id:7, sanskrit:"Marjaryasana", english:"Cat", img: svg.svg7},
  {id:8, sanskrit:"Bitilasana", english:"Cow", img: svg.svg8},
  {id:9, sanskrit:"Utkatasana", english:"Chair", img: svg.svg9},
  {id:10, sanskrit:"Balasana", english:"Child's Pose", img: svg.svg10},
  {id:11, sanskrit:"Sivasana", english:"Corpse", img: svg.svg11},
  {id:12, sanskrit:"Alanasana", english:"Crescent Lunge", img: svg.svg12},
  {id:13, sanskrit:"Bakasana", english:"Crow", img: svg.svg13},
  {id:14, sanskrit:"Ardha Pincha Mayurasana", english:"Dolphin", img: svg.svg14},
  {id:15, sanskrit:"Adho Mukha Svanasana", english:"Downward-Facing Dog", img: svg.svg15},
  {id:16, sanskrit:"Garudasana", english:"Eagle", img: svg.svg16},
  {id:17, sanskrit:"Utthita Hasta Padangusthasana", english:"Extended Hand to Toe", img: svg.svg17},
  {id:18, sanskrit:"Utthita Parsvakonasana", english:"Extended Side Angle", img: svg.svg18},
  {id:19, sanskrit:"Pincha Mayurasana", english:"Forearm Stand", img: svg.svg19},
  {id:20, sanskrit:"Uttanasana", english:"Forward Bend with Shoulder Opener", img: svg.svg20},
  {id:21, sanskrit:"Ardha Chandrasana", english:"Half-Moon", img: svg.svg21},
  {id:22, sanskrit:"Adho Mukha Vrksasana", english:"Handstand", img: svg.svg22},
  {id:23, sanskrit:"Anjaneyasana", english:"Low Lunge", img: svg.svg23},
  {id:24, sanskrit:"Supta Kapotasana", english:"Pigeon", img: svg.svg24},
  {id:25, sanskrit:"Eka Pada Rajakapotasana", english:"King Pigeon", img: svg.svg25},
  {id:26, sanskrit:"Phalakasana", english:"Plank", img: svg.svg26},
  {id:27, sanskrit:"Halasana", english:"Plow", img: svg.svg27},
  {id:28, sanskrit:"Parsvottanasana", english:"Pyramid", img: svg.svg28},
  {id:29, sanskrit:"Parsva Virabhadrasana", english:"Reverse Warrior", img: svg.svg29},
  {id:30, sanskrit:"Paschimottanasana", english:"Seated Forward Bend", img: svg.svg30},
  {id:31, sanskrit:"Padmasana", english:"Lotus", img: svg.svg31},
  {id:32, sanskrit:"Ardha Matsyendrasana", english:"Half Lord of the Fishes", img: svg.svg32},
  {id:33, sanskrit:"Salamba Sarvangasana", english:"Shoulder Stand", img: svg.svg33},
  {id:34, sanskrit:"Vasisthasana", english:"Side Plank", img: svg.svg34},
  {id:35, sanskrit:"Salamba Bhujangasana", english:"Sphinx", img: svg.svg35},
  {id:36, sanskrit:"Hanumanasana", english:"Splits", img: svg.svg36},
  {id:37, sanskrit:"Malasana", english:"Squat", img: svg.svg37},
  {id:38, sanskrit:"Uttanasana", english:"Standing Forward Bend", img: svg.svg38},
  {id:39, sanskrit:"Ashta Chandrasana", english:"Crescent Moon", img: svg.svg39},
  {id:40, sanskrit:"Upavistha Konasana", english:"Side Splits", img: svg.svg40},
  {id:41, sanskrit:"Vrksasana", english:"Tree", img: svg.svg41},
  {id:42, sanskrit:"Trikonasana", english:"Triangle", img: svg.svg42},
  {id:43, sanskrit:"Urdhva Mukha Svsnssana", english:"Upward-Facing Dog", img: svg.svg43},
  {id:44, sanskrit:"Virabhadrasana One", english:"Warrior One", img: svg.svg44},
  {id:45, sanskrit:"Virabhadrasana Two", english:"Warrior Two", img: svg.svg45},
  {id:46, sanskrit:"Virabhadrasana Three", english:"Warrior Three", img: svg.svg46},
  {id:47, sanskrit:"Urdhva Dhanurasana", english:"Wheel", img: svg.svg47},
  {id:48, sanskrit:"Camatkarasana", english:"Wild Thing", img: svg.svg48}
]

module.exports = {poses}
