const svg = require('./svg')

const poses = [
  {id:1, sanskrit:"Navasana", english:"Boat", svg: svg.svg1},
  {id:2, sanskrit:"Ardha Navasana", english:"Half-Boat", svg: svg.svg2},
  {id:3, sanskrit:"Dhanurasana", english:"Bow", svg: svg.svg3},
  {id:4, sanskrit:"Setu Bandha Sarvangasana", english:"Bridge", svg: svg.svg4},
  {id:5, sanskrit:"Baddha Konasana", english:"Butterfly", svg: svg.svg5},
  {id:6, sanskrit:"Ustrasana", english:"Camel", svg: svg.svg6},
  {id:7, sanskrit:"Marjaryasana", english:"Cat", svg: svg.svg7},
  {id:8, sanskrit:"Bitilasana", english:"Cow", svg: svg.svg8},
  {id:9, sanskrit:"Utkatasana", english:"Chair", svg: svg.svg9},
  {id:10, sanskrit:"Balasana", english:"Child's Pose", svg: svg.svg10},
  {id:11, sanskrit:"Sivasana", english:"Corpse", svg: svg.svg11},
  {id:12, sanskrit:"Alanasana", english:"Crescent Lunge", svg: svg.svg12},
  {id:13, sanskrit:"Bakasana", english:"Crow", svg: svg.svg13},
  {id:14, sanskrit:"Ardha Pincha Mayurasana", english:"Dolphin", svg: svg.svg14},
  {id:15, sanskrit:"Adho Mukha Svanasana", english:"Downward-Facing Dog", svg: svg.svg15},
  {id:16, sanskrit:"Garudasana", english:"Eagle", svg: svg.svg16},
  {id:17, sanskrit:"Utthita Hasta Padangusthasana", english:"Extended Hand to Toe", svg: svg.svg17},
  {id:18, sanskrit:"Utthita Parsvakonasana", english:"Extended Side Angle", svg: svg.svg18},
  {id:19, sanskrit:"Pincha Mayurasana", english:"Forearm Stand", svg: svg.svg19},
  {id:20, sanskrit:"Uttanasana", english:"Forward Bend with Shoulder Opener", svg: svg.svg20},
  {id:21, sanskrit:"Ardha Chandrasana", english:"Half-Moon", svg: svg.svg21},
  {id:22, sanskrit:"Adho Mukha Vrksasana", english:"Handstand", svg: svg.svg22},
  {id:23, sanskrit:"Anjaneyasana", english:"Low Lunge", svg: svg.svg23},
  {id:24, sanskrit:"Supta Kapotasana", english:"Pigeon", svg: svg.svg24},
  {id:25, sanskrit:"Eka Pada Rajakapotasana", english:"King Pigeon", svg: svg.svg25},
  {id:26, sanskrit:"Phalakasana", english:"Plank", svg: svg.svg26},
  {id:27, sanskrit:"Halasana", english:"Plow", svg: svg.svg27},
  {id:28, sanskrit:"Parsvottanasana", english:"Pyramid", svg: svg.svg28},
  {id:29, sanskrit:"Parsva Virabhadrasana", english:"Reverse Warrior", svg: svg.svg29},
  {id:30, sanskrit:"Paschimottanasana", english:"Seated Forward Bend", svg: svg.svg30},
  {id:31, sanskrit:"Padmasana", english:"Lotus", svg: svg.svg31},
  {id:32, sanskrit:"Ardha Matsyendrasana", english:"Half Lord of the Fishes", svg: svg.svg32},
  {id:33, sanskrit:"Salamba Sarvangasana", english:"Shoulder Stand", svg: svg.svg33},
  {id:34, sanskrit:"Vasisthasana", english:"Side Plank", svg: svg.svg34},
  {id:35, sanskrit:"Salamba Bhujangasana", english:"Sphinx", svg: svg.svg35},
  {id:36, sanskrit:"Hanumanasana", english:"Splits", svg: svg.svg36},
  {id:37, sanskrit:"Malasana", english:"Squat", svg: svg.svg37},
  {id:38, sanskrit:"Uttanasana", english:"Standing Forward Bend", svg: svg.svg38},
  {id:39, sanskrit:"Ashta Chandrasana", english:"Crescent Moon", svg: svg.svg39},
  {id:40, sanskrit:"Upavistha Konasana", english:"Side Splits", svg: svg.svg40},
  {id:41, sanskrit:"Vrksasana", english:"Tree", svg: svg.svg41},
  {id:42, sanskrit:"Trikonasana", english:"Triangle", svg: svg.svg42},
  {id:43, sanskrit:"Urdhva Mukha Svsnssana", english:"Upward-Facing Dog", svg: svg.svg43},
  {id:44, sanskrit:"Virabhadrasana One", english:"Warrior One", svg: svg.svg44},
  {id:45, sanskrit:"Virabhadrasana Two", english:"Warrior Two", svg: svg.svg45},
  {id:46, sanskrit:"Virabhadrasana Three", english:"Warrior Three", svg: svg.svg46},
  {id:47, sanskrit:"Urdhva Dhanurasana", english:"Wheel", svg: svg.svg47},
  {id:48, sanskrit:"Camatkarasana", english:"Wild Thing", svg: svg.svg48}
]

module.exports = {poses}
